// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adjpowakxjmbysajpkmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkanBvd2FreGptYnlzYWpwa21iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNjUyOTcsImV4cCI6MjA1OTk0MTI5N30.A75gwX7qzsInYtI5wLRcomck81v3V3X0Gkyi-91r600";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);